export const Countries = [
  {
    label: 'Afghanistan',
    value: 'Afghanistan',
    flag: '🇦🇫',
    dialCode: '+93',
    isoCode: 'AF',
  },
  {
    label: 'Albania',
    value: 'Albania',
    flag: '🇦🇱',
    dialCode: '+355',
    isoCode: 'AL',
  },
  {
    label: 'Algeria',
    value: 'Algeria',
    flag: '🇩🇿',
    dialCode: '+213',
    isoCode: 'DZ',
  },
  {
    label: 'Andorra',
    value: 'Andorra',
    flag: '🇦🇩',
    dialCode: '+376',
    isoCode: 'AD',
  },
  {
    label: 'Angola',
    value: 'Angola',
    flag: '🇦🇴',
    dialCode: '+244',
    isoCode: 'AO',
  },
  {
    label: 'Argentina',
    value: 'Argentina',
    flag: '🇦🇷',
    dialCode: '+54',
    isoCode: 'AR',
  },
  {
    label: 'Armenia',
    value: 'Armenia',
    flag: '🇦🇲',
    dialCode: '+374',
    isoCode: 'AM',
  },
  {
    label: 'Australia',
    value: 'Australia',
    flag: '🇦🇺',
    dialCode: '+61',
    isoCode: 'AU',
  },
  {
    label: 'Austria',
    value: 'Austria',
    flag: '🇦🇹',
    dialCode: '+43',
    isoCode: 'AT',
  },
  {
    label: 'Azerbaijan',
    value: 'Azerbaijan',
    flag: '🇦🇿',
    dialCode: '+994',
    isoCode: 'AZ',
  },
  {
    label: 'Bahamas',
    value: 'Bahamas',
    flag: '🇧🇸',
    dialCode: '+1-242',
    isoCode: 'BS',
  },
  {
    label: 'Bahrain',
    value: 'Bahrain',
    flag: '🇧🇭',
    dialCode: '+973',
    isoCode: 'BH',
  },
  {
    label: 'Bangladesh',
    value: 'Bangladesh',
    flag: '🇧🇩',
    dialCode: '+880',
    isoCode: 'BD',
  },
  {
    label: 'Barbados',
    value: 'Barbados',
    flag: '🇧🇧',
    dialCode: '+1-246',
    isoCode: 'BB',
  },
  {
    label: 'Belarus',
    value: 'Belarus',
    flag: '🇧🇾',
    dialCode: '+375',
    isoCode: 'BY',
  },
  {
    label: 'Belgium',
    value: 'Belgium',
    flag: '🇧🇪',
    dialCode: '+32',
    isoCode: 'BE',
  },
  {
    label: 'Belize',
    value: 'Belize',
    flag: '🇧🇿',
    dialCode: '+501',
    isoCode: 'BZ',
  },
  {
    label: 'Benin',
    value: 'Benin',
    flag: '🇧🇯',
    dialCode: '+229',
    isoCode: 'BJ',
  },
  {
    label: 'Bhutan',
    value: 'Bhutan',
    flag: '🇧🇹',
    dialCode: '+975',
    isoCode: 'BT',
  },
  {
    label: 'Bolivia',
    value: 'Bolivia',
    flag: '🇧🇴',
    dialCode: '+591',
    isoCode: 'BO',
  },
  {
    label: 'Bosnia and Herzegovina',
    value: 'Bosnia and Herzegovina',
    flag: '🇧🇦',
    dialCode: '+387',
    isoCode: 'BA',
  },
  {
    label: 'Botswana',
    value: 'Botswana',
    flag: '🇧🇼',
    dialCode: '+267',
    isoCode: 'BW',
  },
  {
    label: 'Brazil',
    value: 'Brazil',
    flag: '🇧🇷',
    dialCode: '+55',
    isoCode: 'BR',
  },
  {
    label: 'Brunei',
    value: 'Brunei',
    flag: '🇧🇳',
    dialCode: '+673',
    isoCode: 'BN',
  },
  {
    label: 'Bulgaria',
    value: 'Bulgaria',
    flag: '🇧🇬',
    dialCode: '+359',
    isoCode: 'BG',
  },
  {
    label: 'Burkina Faso',
    value: 'Burkina Faso',
    flag: '🇧🇫',
    dialCode: '+226',
    isoCode: 'BF',
  },
  {
    label: 'Burundi',
    value: 'Burundi',
    flag: '🇧🇮',
    dialCode: '+257',
    isoCode: 'BI',
  },
  {
    label: 'Cabo Verde',
    value: 'Cabo Verde',
    flag: '🇨🇻',
    dialCode: '+238',
    isoCode: 'CV',
  },
  {
    label: 'Cambodia',
    value: 'Cambodia',
    flag: '🇰🇭',
    dialCode: '+855',
    isoCode: 'KH',
  },
  {
    label: 'Cameroon',
    value: 'Cameroon',
    flag: '🇨🇲',
    dialCode: '+237',
    isoCode: 'CM',
  },
  {
    label: 'Canada',
    value: 'Canada',
    flag: '🇨🇦',
    dialCode: '+1',
    isoCode: 'CA',
  },
  {
    label: 'Central African Republic',
    value: 'Central African Republic',
    flag: '🇨🇫',
    dialCode: '+236',
    isoCode: 'CF',
  },
  {
    label: 'Chad',
    value: 'Chad',
    flag: '🇹🇩',
    dialCode: '+235',
    isoCode: 'TD',
  },
  {
    label: 'Chile',
    value: 'Chile',
    flag: '🇨🇱',
    dialCode: '+56',
    isoCode: 'CL',
  },
  {
    label: 'China',
    value: 'China',
    flag: '🇨🇳',
    dialCode: '+86',
    isoCode: 'CN',
  },
  {
    label: 'Colombia',
    value: 'Colombia',
    flag: '🇨🇴',
    dialCode: '+57',
    isoCode: 'CO',
  },
  {
    label: 'Comoros',
    value: 'Comoros',
    flag: '🇰🇲',
    dialCode: '+269',
    isoCode: 'KM',
  },
  {
    label: 'Congo (Congo-Brazzaville)',
    value: 'Congo',
    flag: '🇨🇬',
    dialCode: '+242',
    isoCode: 'CG',
  },
  {
    label: 'Costa Rica',
    value: 'Costa Rica',
    flag: '🇨🇷',
    dialCode: '+506',
    isoCode: 'CR',
  },
  {
    label: 'Croatia',
    value: 'Croatia',
    flag: '🇭🇷',
    dialCode: '+385',
    isoCode: 'HR',
  },
  {
    label: 'Cuba',
    value: 'Cuba',
    flag: '🇨🇺',
    dialCode: '+53',
    isoCode: 'CU',
  },
  {
    label: 'Cyprus',
    value: 'Cyprus',
    flag: '🇨🇾',
    dialCode: '+357',
    isoCode: 'CY',
  },
  {
    label: 'Czechia (Czech Republic)',
    value: 'Czechia',
    flag: '🇨🇿',
    dialCode: '+420',
    isoCode: 'CZ',
  },
  {
    label: 'Denmark',
    value: 'Denmark',
    flag: '🇩🇰',
    dialCode: '+45',
    isoCode: 'DK',
  },
  {
    label: 'Djibouti',
    value: 'Djibouti',
    flag: '🇩🇯',
    dialCode: '+253',
    isoCode: 'DJ',
  },
  {
    label: 'Dominica',
    value: 'Dominica',
    flag: '🇩🇲',
    dialCode: '+1-767',
    isoCode: 'DM',
  },
  {
    label: 'Dominican Republic',
    value: 'Dominican Republic',
    flag: '🇩🇴',
    dialCode: '+1-809, +1-829, +1-849',
    isoCode: 'DO',
  },
  {
    label: 'Ecuador',
    value: 'Ecuador',
    flag: '🇪🇨',
    dialCode: '+593',
    isoCode: 'EC',
  },
  {
    label: 'Egypt',
    value: 'Egypt',
    flag: '🇪🇬',
    dialCode: '+20',
    isoCode: 'EG',
  },
  {
    label: 'El Salvador',
    value: 'El Salvador',
    flag: '🇸🇻',
    dialCode: '+503',
    isoCode: 'SV',
  },
  {
    label: 'Equatorial Guinea',
    value: 'Equatorial Guinea',
    flag: '🇬🇶',
    dialCode: '+240',
    isoCode: 'GQ',
  },
  {
    label: 'Eritrea',
    value: 'Eritrea',
    flag: '🇪🇷',
    dialCode: '+291',
    isoCode: 'ER',
  },
  {
    label: 'Estonia',
    value: 'Estonia',
    flag: '🇪🇪',
    dialCode: '+372',
    isoCode: 'EE',
  },
  {
    label: 'Eswatini (fmr. "Swaziland")',
    value: 'Eswatini',
    flag: '🇸🇿',
    dialCode: '+268',
    isoCode: 'SZ',
  },
  {
    label: 'Ethiopia',
    value: 'Ethiopia',
    flag: '🇪🇹',
    dialCode: '+251',
    isoCode: 'ET',
  },
  {
    label: 'Fiji',
    value: 'Fiji',
    flag: '🇫🇯',
    dialCode: '+679',
    isoCode: 'FJ',
  },
  {
    label: 'Finland',
    value: 'Finland',
    flag: '🇫🇮',
    dialCode: '+358',
    isoCode: 'FI',
  },
  {
    label: 'France',
    value: 'France',
    flag: '🇫🇷',
    dialCode: '+33',
    isoCode: 'FR',
  },
  {
    label: 'Gabon',
    value: 'Gabon',
    flag: '🇬🇦',
    dialCode: '+241',
    isoCode: 'GA',
  },
  {
    label: 'Gambia',
    value: 'Gambia',
    flag: '🇬🇲',
    dialCode: '+220',
    isoCode: 'GM',
  },
  {
    label: 'Georgia',
    value: 'Georgia',
    flag: '🇬🇪',
    dialCode: '+995',
    isoCode: 'GE',
  },
  {
    label: 'Germany',
    value: 'Germany',
    flag: '🇩🇪',
    dialCode: '+49',
    isoCode: 'DE',
  },
  {
    label: 'Ghana',
    value: 'Ghana',
    flag: '🇬🇭',
    dialCode: '+233',
    isoCode: 'GH',
  },
  {
    label: 'Greece',
    value: 'Greece',
    flag: '🇬🇷',
    dialCode: '+30',
    isoCode: 'GR',
  },
  {
    label: 'Grenada',
    value: 'Grenada',
    flag: '🇬🇩',
    dialCode: '+1-473',
    isoCode: 'GD',
  },
  {
    label: 'Guatemala',
    value: 'Guatemala',
    flag: '🇬🇹',
    dialCode: '+502',
    isoCode: 'GT',
  },
  {
    label: 'Guinea',
    value: 'Guinea',
    flag: '🇬🇳',
    dialCode: '+224',
    isoCode: 'GN',
  },
  {
    label: 'Guinea-Bissau',
    value: 'Guinea-Bissau',
    flag: '🇬🇼',
    dialCode: '+245',
    isoCode: 'GW',
  },
  {
    label: 'Guyana',
    value: 'Guyana',
    flag: '🇬🇾',
    dialCode: '+592',
    isoCode: 'GY',
  },
  {
    label: 'Haiti',
    value: 'Haiti',
    flag: '🇭🇹',
    dialCode: '+509',
    isoCode: 'HT',
  },
  {
    label: 'Honduras',
    value: 'Honduras',
    flag: '🇭🇳',
    dialCode: '+504',
    isoCode: 'HN',
  },
  {
    label: 'Hungary',
    value: 'Hungary',
    flag: '🇭🇺',
    dialCode: '+36',
    isoCode: 'HU',
  },
  {
    label: 'Iceland',
    value: 'Iceland',
    flag: '🇮🇸',
    dialCode: '+354',
    isoCode: 'IS',
  },
  {
    label: 'India',
    value: 'India',
    flag: '🇮🇳',
    dialCode: '+91',
    isoCode: 'IN',
  },
  {
    label: 'Indonesia',
    value: 'Indonesia',
    flag: '🇮🇩',
    dialCode: '+62',
    isoCode: 'ID',
  },
  {
    label: 'Iran',
    value: 'Iran',
    flag: '🇮🇷',
    dialCode: '+98',
    isoCode: 'IR',
  },
  {
    label: 'Iraq',
    value: 'Iraq',
    flag: '🇮🇶',
    dialCode: '+964',
    isoCode: 'IQ',
  },
  {
    label: 'Ireland',
    value: 'Ireland',
    flag: '🇮🇪',
    dialCode: '+353',
    isoCode: 'IE',
  },
  {
    label: 'Israel',
    value: 'Israel',
    flag: '🇮🇱',
    dialCode: '+972',
    isoCode: 'IL',
  },
  {
    label: 'Italy',
    value: 'Italy',
    flag: '🇮🇹',
    dialCode: '+39',
    isoCode: 'IT',
  },
  {
    label: 'Jamaica',
    value: 'Jamaica',
    flag: '🇯🇲',
    dialCode: '+1-876',
    isoCode: 'JM',
  },
  {
    label: 'Japan',
    value: 'Japan',
    flag: '🇯🇵',
    dialCode: '+81',
    isoCode: 'JP',
  },
  {
    label: 'Jordan',
    value: 'Jordan',
    flag: '🇯🇴',
    dialCode: '+962',
    isoCode: 'JO',
  },
  {
    label: 'Kazakhstan',
    value: 'Kazakhstan',
    flag: '🇰🇿',
    dialCode: '+7',
    isoCode: 'KZ',
  },
  {
    label: 'Kenya',
    value: 'Kenya',
    flag: '🇰🇪',
    dialCode: '+254',
    isoCode: 'KE',
  },
  {
    label: 'Kiribati',
    value: 'Kiribati',
    flag: '🇰🇮',
    dialCode: '+686',
    isoCode: 'KI',
  },
  {
    label: 'Kuwait',
    value: 'Kuwait',
    flag: '🇰🇼',
    dialCode: '+965',
    isoCode: 'KW',
  },
  {
    label: 'Kyrgyzstan',
    value: 'Kyrgyzstan',
    flag: '🇰🇬',
    dialCode: '+996',
    isoCode: 'KG',
  },
  {
    label: 'Laos',
    value: 'Laos',
    flag: '🇱🇦',
    dialCode: '+856',
    isoCode: 'LA',
  },
  {
    label: 'Latvia',
    value: 'Latvia',
    flag: '🇱🇻',
    dialCode: '+371',
    isoCode: 'LV',
  },
  {
    label: 'Lebanon',
    value: 'Lebanon',
    flag: '🇱🇧',
    dialCode: '+961',
    isoCode: 'LB',
  },
  {
    label: 'Lesotho',
    value: 'Lesotho',
    flag: '🇱🇸',
    dialCode: '+266',
    isoCode: 'LS',
  },
  {
    label: 'Liberia',
    value: 'Liberia',
    flag: '🇱🇷',
    dialCode: '+231',
    isoCode: 'LR',
  },
  {
    label: 'Libya',
    value: 'Libya',
    flag: '🇱🇾',
    dialCode: '+218',
    isoCode: 'LY',
  },
  {
    label: 'Liechtenstein',
    value: 'Liechtenstein',
    flag: '🇱🇮',
    dialCode: '+423',
    isoCode: 'LI',
  },
  {
    label: 'Lithuania',
    value: 'Lithuania',
    flag: '🇱🇹',
    dialCode: '+370',
    isoCode: 'LT',
  },
  {
    label: 'Luxembourg',
    value: 'Luxembourg',
    flag: '🇱🇺',
    dialCode: '+352',
    isoCode: 'LU',
  },
  {
    label: 'Madagascar',
    value: 'Madagascar',
    flag: '🇲🇬',
    dialCode: '+261',
    isoCode: 'MG',
  },
  {
    label: 'Malawi',
    value: 'Malawi',
    flag: '🇲🇼',
    dialCode: '+265',
    isoCode: 'MW',
  },
  {
    label: 'Malaysia',
    value: 'Malaysia',
    flag: '🇲🇾',
    dialCode: '+60',
    isoCode: 'MY',
  },
  {
    label: 'Maldives',
    value: 'Maldives',
    flag: '🇲🇻',
    dialCode: '+960',
    isoCode: 'MV',
  },
  {
    label: 'Mali',
    value: 'Mali',
    flag: '🇲🇱',
    dialCode: '+223',
    isoCode: 'ML',
  },
  {
    label: 'Malta',
    value: 'Malta',
    flag: '🇲🇹',
    dialCode: '+356',
    isoCode: 'MT',
  },
  {
    label: 'Marshall Islands',
    value: 'Marshall Islands',
    flag: '🇲🇭',
    dialCode: '+692',
    isoCode: 'MH',
  },
  {
    label: 'Mauritania',
    value: 'Mauritania',
    flag: '🇲🇷',
    dialCode: '+222',
    isoCode: 'MR',
  },
  {
    label: 'Mauritius',
    value: 'Mauritius',
    flag: '🇲🇺',
    dialCode: '+230',
    isoCode: 'MU',
  },
  {
    label: 'Mexico',
    value: 'Mexico',
    flag: '🇲🇽',
    dialCode: '+52',
    isoCode: 'MX',
  },
  {
    label: 'Micronesia',
    value: 'Micronesia',
    flag: '🇫🇲',
    dialCode: '+691',
    isoCode: 'FM',
  },
  {
    label: 'Moldova',
    value: 'Moldova',
    flag: '🇲🇩',
    dialCode: '+373',
    isoCode: 'MD',
  },
  {
    label: 'Monaco',
    value: 'Monaco',
    flag: '🇲🇨',
    dialCode: '+377',
    isoCode: 'MC',
  },
  {
    label: 'Mongolia',
    value: 'Mongolia',
    flag: '🇲🇳',
    dialCode: '+976',
    isoCode: 'MN',
  },
  {
    label: 'Montenegro',
    value: 'Montenegro',
    flag: '🇲🇪',
    dialCode: '+382',
    isoCode: 'ME',
  },
  {
    label: 'Morocco',
    value: 'Morocco',
    flag: '🇲🇦',
    dialCode: '+212',
    isoCode: 'MA',
  },
  {
    label: 'Mozambique',
    value: 'Mozambique',
    flag: '🇲🇿',
    dialCode: '+258',
    isoCode: 'MZ',
  },
  {
    label: 'Myanmar (formerly Burma)',
    value: 'Myanmar',
    flag: '🇲🇲',
    dialCode: '+95',
    isoCode: 'MM',
  },
  {
    label: 'Namibia',
    value: 'Namibia',
    flag: '🇳🇦',
    dialCode: '+264',
    isoCode: 'NA',
  },
  {
    label: 'Nauru',
    value: 'Nauru',
    flag: '🇳🇷',
    dialCode: '+674',
    isoCode: 'NR',
  },
  {
    label: 'Nepal',
    value: 'Nepal',
    flag: '🇳🇵',
    dialCode: '+977',
    isoCode: 'NP',
  },
  {
    label: 'Netherlands',
    value: 'Netherlands',
    flag: '🇳🇱',
    dialCode: '+31',
    isoCode: 'NL',
  },
  {
    label: 'New Zealand',
    value: 'New Zealand',
    flag: '🇳🇿',
    dialCode: '+64',
    isoCode: 'NZ',
  },
  {
    label: 'Nicaragua',
    value: 'Nicaragua',
    flag: '🇳🇮',
    dialCode: '+505',
    isoCode: 'NI',
  },
  {
    label: 'Niger',
    value: 'Niger',
    flag: '🇳🇪',
    dialCode: '+227',
    isoCode: 'NE',
  },
  {
    label: 'Nigeria',
    value: 'Nigeria',
    flag: '🇳🇬',
    dialCode: '+234',
    isoCode: 'NG',
  },
  {
    label: 'North Korea',
    value: 'North Korea',
    flag: '🇰🇵',
    dialCode: '+850',
    isoCode: 'KP',
  },
  {
    label: 'North Macedonia',
    value: 'North Macedonia',
    flag: '🇲🇰',
    dialCode: '+389',
    isoCode: 'MK',
  },
  {
    label: 'Norway',
    value: 'Norway',
    flag: '🇳🇴',
    dialCode: '+47',
    isoCode: 'NO',
  },
  {
    label: 'Oman',
    value: 'Oman',
    flag: '🇴🇲',
    dialCode: '+968',
    isoCode: 'OM',
  },
  {
    label: 'Pakistan',
    value: 'Pakistan',
    flag: '🇵🇰',
    dialCode: '+92',
    isoCode: 'PK',
  },
  {
    label: 'Palau',
    value: 'Palau',
    flag: '🇵🇼',
    dialCode: '+680',
    isoCode: 'PW',
  },
  {
    label: 'Palestine State',
    value: 'Palestine',
    flag: '🇵🇸',
    dialCode: '+970',
    isoCode: 'PS',
  },
  {
    label: 'Panama',
    value: 'Panama',
    flag: '🇵🇦',
    dialCode: '+507',
    isoCode: 'PA',
  },
  {
    label: 'Papua New Guinea',
    value: 'Papua New Guinea',
    flag: '🇵🇬',
    dialCode: '+675',
    isoCode: 'PG',
  },
  {
    label: 'Paraguay',
    value: 'Paraguay',
    flag: '🇵🇾',
    dialCode: '+595',
    isoCode: 'PY',
  },
  {
    label: 'Peru',
    value: 'Peru',
    flag: '🇵🇪',
    dialCode: '+51',
    isoCode: 'PE',
  },
  {
    label: 'Philippines',
    value: 'Philippines',
    flag: '🇵🇭',
    dialCode: '+63',
    isoCode: 'PH',
  },
  {
    label: 'Poland',
    value: 'Poland',
    flag: '🇵🇱',
    dialCode: '+48',
    isoCode: 'PL',
  },
  {
    label: 'Portugal',
    value: 'Portugal',
    flag: '🇵🇹',
    dialCode: '+351',
    isoCode: 'PT',
  },
  {
    label: 'Qatar',
    value: 'Qatar',
    flag: '🇶🇦',
    dialCode: '+974',
    isoCode: 'QA',
  },
  {
    label: 'Romania',
    value: 'Romania',
    flag: '🇷🇴',
    dialCode: '+40',
    isoCode: 'RO',
  },
  {
    label: 'Russia',
    value: 'Russia',
    flag: '🇷🇺',
    dialCode: '+7',
    isoCode: 'RU',
  },
  {
    label: 'Rwanda',
    value: 'Rwanda',
    flag: '🇷🇼',
    dialCode: '+250',
    isoCode: 'RW',
  },
  {
    label: 'Saint Kitts and Nevis',
    value: 'Saint Kitts and Nevis',
    flag: '🇰🇳',
    dialCode: '+1-869',
    isoCode: 'KN',
  },
  {
    label: 'Saint Lucia',
    value: 'Saint Lucia',
    flag: '🇱🇨',
    dialCode: '+1-758',
    isoCode: 'LC',
  },
  {
    label: 'Saint Vincent and the Grenadines',
    value: 'Saint Vincent and the Grenadines',
    flag: '🇻🇨',
    dialCode: '+1-784',
    isoCode: 'VC',
  },
  {
    label: 'Samoa',
    value: 'Samoa',
    flag: '🇼🇸',
    dialCode: '+685',
    isoCode: 'WS',
  },
  {
    label: 'San Marino',
    value: 'San Marino',
    flag: '🇸🇲',
    dialCode: '+378',
    isoCode: 'SM',
  },
  {
    label: 'Sao Tome and Principe',
    value: 'Sao Tome and Principe',
    flag: '🇸🇹',
    dialCode: '+239',
    isoCode: 'ST',
  },
  {
    label: 'Saudi Arabia',
    value: 'Saudi Arabia',
    flag: '🇸🇦',
    dialCode: '+966',
    isoCode: 'SA',
  },
  {
    label: 'Senegal',
    value: 'Senegal',
    flag: '🇸🇳',
    dialCode: '+221',
    isoCode: 'SN',
  },
  {
    label: 'Serbia',
    value: 'Serbia',
    flag: '🇷🇸',
    dialCode: '+381',
    isoCode: 'RS',
  },
  {
    label: 'Seychelles',
    value: 'Seychelles',
    flag: '🇸🇨',
    dialCode: '+248',
    isoCode: 'SC',
  },
  {
    label: 'Sierra Leone',
    value: 'Sierra Leone',
    flag: '🇸🇱',
    dialCode: '+232',
    isoCode: 'SL',
  },
  {
    label: 'Singapore',
    value: 'Singapore',
    flag: '🇸🇬',
    dialCode: '+65',
    isoCode: 'SG',
  },
  {
    label: 'Slovakia',
    value: 'Slovakia',
    flag: '🇸🇰',
    dialCode: '+421',
    isoCode: 'SK',
  },
  {
    label: 'Slovenia',
    value: 'Slovenia',
    flag: '🇸🇮',
    dialCode: '+386',
    isoCode: 'SI',
  },
  {
    label: 'Solomon Islands',
    value: 'Solomon Islands',
    flag: '🇸🇧',
    dialCode: '+677',
    isoCode: 'SB',
  },
  {
    label: 'Somalia',
    value: 'Somalia',
    flag: '🇸🇴',
    dialCode: '+252',
    isoCode: 'SO',
  },
  {
    label: 'South Africa',
    value: 'South Africa',
    flag: '🇿🇦',
    dialCode: '+27',
    isoCode: 'ZA',
  },
  {
    label: 'South Korea',
    value: 'South Korea',
    flag: '🇰🇷',
    dialCode: '+82',
    isoCode: 'KR',
  },
  {
    label: 'South Sudan',
    value: 'South Sudan',
    flag: '🇸🇸',
    dialCode: '+211',
    isoCode: 'SS',
  },
  {
    label: 'Spain',
    value: 'Spain',
    flag: '🇪🇸',
    dialCode: '+34',
    isoCode: 'ES',
  },
  {
    label: 'Sri Lanka',
    value: 'Sri Lanka',
    flag: '🇱🇰',
    dialCode: '+94',
    isoCode: 'LK',
  },
  {
    label: 'Sudan',
    value: 'Sudan',
    flag: '🇸🇩',
    dialCode: '+249',
    isoCode: 'SD',
  },
  {
    label: 'Suriname',
    value: 'Suriname',
    flag: '🇸🇷',
    dialCode: '+597',
    isoCode: 'SR',
  },
  {
    label: 'Sweden',
    value: 'Sweden',
    flag: '🇸🇪',
    dialCode: '+46',
    isoCode: 'SE',
  },
  {
    label: 'Switzerland',
    value: 'Switzerland',
    flag: '🇨🇭',
    dialCode: '+41',
    isoCode: 'CH',
  },
  {
    label: 'Syria',
    value: 'Syria',
    flag: '🇸🇾',
    dialCode: '+963',
    isoCode: 'SY',
  },
  {
    label: 'Taiwan',
    value: 'Taiwan',
    flag: '🇹🇼',
    dialCode: '+886',
    isoCode: 'TW',
  },
  {
    label: 'Tajikistan',
    value: 'Tajikistan',
    flag: '🇹🇯',
    dialCode: '+992',
    isoCode: 'TJ',
  },
  {
    label: 'Tanzania',
    value: 'Tanzania',
    flag: '🇹🇿',
    dialCode: '+255',
    isoCode: 'TZ',
  },
  {
    label: 'Thailand',
    value: 'Thailand',
    flag: '🇹🇭',
    dialCode: '+66',
    isoCode: 'TH',
  },
  {
    label: 'Timor-Leste',
    value: 'Timor-Leste',
    flag: '🇹🇱',
    dialCode: '+670',
    isoCode: 'TL',
  },
  {
    label: 'Togo',
    value: 'Togo',
    flag: '🇹🇬',
    dialCode: '+228',
    isoCode: 'TG',
  },
  {
    label: 'Tonga',
    value: 'Tonga',
    flag: '🇹🇴',
    dialCode: '+676',
    isoCode: 'TO',
  },
  {
    label: 'Trinidad and Tobago',
    value: 'Trinidad and Tobago',
    flag: '🇹🇹',
    dialCode: '+1-868',
    isoCode: 'TT',
  },
  {
    label: 'Tunisia',
    value: 'Tunisia',
    flag: '🇹🇳',
    dialCode: '+216',
    isoCode: 'TN',
  },
  {
    label: 'Turkey',
    value: 'Turkey',
    flag: '🇹🇷',
    dialCode: '+90',
    isoCode: 'TR',
  },
  {
    label: 'Turkmenistan',
    value: 'Turkmenistan',
    flag: '🇹🇲',
    dialCode: '+993',
    isoCode: 'TM',
  },
  {
    label: 'Tuvalu',
    value: 'Tuvalu',
    flag: '🇹🇻',
    dialCode: '+688',
    isoCode: 'TV',
  },
  {
    label: 'Uganda',
    value: 'Uganda',
    flag: '🇺🇬',
    dialCode: '+256',
    isoCode: 'UG',
  },
  {
    label: 'Ukraine',
    value: 'Ukraine',
    flag: '🇺🇦',
    dialCode: '+380',
    isoCode: 'UA',
  },
  {
    label: 'United Arab Emirates',
    value: 'United Arab Emirates',
    flag: '🇦🇪',
    dialCode: '+971',
    isoCode: 'AE',
  },
  {
    label: 'United Kingdom',
    value: 'United Kingdom',
    flag: '🇬🇧',
    dialCode: '+44',
    isoCode: 'GB',
  },
  {
    label: 'United States',
    value: 'United States',
    flag: '🇺🇸',
    dialCode: '+1',
    isoCode: 'US',
  },
  {
    label: 'Uruguay',
    value: 'Uruguay',
    flag: '🇺🇾',
    dialCode: '+598',
    isoCode: 'UY',
  },
  {
    label: 'Uzbekistan',
    value: 'Uzbekistan',
    flag: '🇺🇿',
    dialCode: '+998',
    isoCode: 'UZ',
  },
  {
    label: 'Vanuatu',
    value: 'Vanuatu',
    flag: '🇻🇺',
    dialCode: '+678',
    isoCode: 'VU',
  },
  {
    label: 'Vatican City',
    value: 'Vatican City',
    flag: '🇻🇦',
    dialCode: '+379',
    isoCode: 'VA',
  },
  {
    label: 'Venezuela',
    value: 'Venezuela',
    flag: '🇻🇪',
    dialCode: '+58',
    isoCode: 'VE',
  },
  {
    label: 'Vietnam',
    value: 'Vietnam',
    flag: '🇻🇳',
    dialCode: '+84',
    isoCode: 'VN',
  },
  {
    label: 'Yemen',
    value: 'Yemen',
    flag: '🇾🇪',
    dialCode: '+967',
    isoCode: 'YE',
  },
  {
    label: 'Zambia',
    value: 'Zambia',
    flag: '🇿🇲',
    dialCode: '+260',
    isoCode: 'ZM',
  },
  {
    label: 'Zimbabwe',
    value: 'Zimbabwe',
    flag: '🇿🇼',
    dialCode: '+263',
    isoCode: 'ZW',
  },
];

export const CountryFlag = isoCode => {
  const flagUrl = `https://flagcdn.com/24x18/${isoCode.toLowerCase()}.png`;
  return (
    // eslint-disable-next-line @next/next/no-img-element
    <img
      key={isoCode}
      src={flagUrl}
      alt={`Flag of ${isoCode}`}
      srcSet={`https://flagcdn.com/48x36/${isoCode.toLowerCase()}.png 2x,
    https://flagcdn.com/72x54/${isoCode.toLowerCase()}.png 3x`}
      width="24"
      height="18"
      loading="lazy"
    />
  );
};

// {Countries.map(item => {
//   return CountryFlag(item.isoCode);
// })}
