export const Countries = [
  {
    label: 'Afghanistan',
    value: 'Afghanistan',
    flag: '🇦🇫',
    dialCode: '+93',
  },
  {
    label: 'Albania',
    value: 'Albania',
    flag: '🇦🇱',
    dialCode: '+355',
  },
  {
    label: 'Algeria',
    value: 'Algeria',
    flag: '🇩🇿',
    dialCode: '+213',
  },
  {
    label: 'Andorra',
    value: 'Andorra',
    flag: '🇦🇩',
    dialCode: '+376',
  },
  {
    label: 'Angola',
    value: 'Angola',
    flag: '🇦🇴',
    dialCode: '+244',
  },
  {
    label: 'Argentina',
    value: 'Argentina',
    flag: '🇦🇷',
    dialCode: '+54',
  },
  {
    label: 'Armenia',
    value: 'Armenia',
    flag: '🇦🇲',
    dialCode: '+374',
  },
  {
    label: 'Australia',
    value: 'Australia',
    flag: '🇦🇺',
    dialCode: '+61',
  },
  {
    label: 'Austria',
    value: 'Austria',
    flag: '🇦🇹',
    dialCode: '+43',
  },
  {
    label: 'Azerbaijan',
    value: 'Azerbaijan',
    flag: '🇦🇿',
    dialCode: '+994',
  },
  {
    label: 'Bahamas',
    value: 'Bahamas',
    flag: '🇧🇸',
    dialCode: '+1-242',
  },
  {
    label: 'Bahrain',
    value: 'Bahrain',
    flag: '🇧🇭',
    dialCode: '+973',
  },
  {
    label: 'Bangladesh',
    value: 'Bangladesh',
    flag: '🇧🇩',
    dialCode: '+880',
  },
  {
    label: 'Barbados',
    value: 'Barbados',
    flag: '🇧🇧',
    dialCode: '+1-246',
  },
  {
    label: 'Belarus',
    value: 'Belarus',
    flag: '🇧🇾',
    dialCode: '+375',
  },
  {
    label: 'Belgium',
    value: 'Belgium',
    flag: '🇧🇪',
    dialCode: '+32',
  },
  {
    label: 'Belize',
    value: 'Belize',
    flag: '🇧🇿',
    dialCode: '+501',
  },
  {
    label: 'Benin',
    value: 'Benin',
    flag: '🇧🇯',
    dialCode: '+229',
  },
  {
    label: 'Bhutan',
    value: 'Bhutan',
    flag: '🇧🇹',
    dialCode: '+975',
  },
  {
    label: 'Bolivia',
    value: 'Bolivia',
    flag: '🇧🇴',
    dialCode: '+591',
  },
  {
    label: 'Bosnia and Herzegovina',
    value: 'BosniaandHerzegovina',
    flag: '🇧🇦',
    dialCode: '+387',
  },
  {
    label: 'Botswana',
    value: 'Botswana',
    flag: '🇧🇼',
    dialCode: '+267',
  },
  {
    label: 'Brazil',
    value: 'Brazil',
    flag: '🇧🇷',
    dialCode: '+55',
  },
  {
    label: 'Brunei',
    value: 'Brunei',
    flag: '🇧🇳',
    dialCode: '+673',
  },
  {
    label: 'Bulgaria',
    value: 'Bulgaria',
    flag: '🇧🇬',
    dialCode: '+359',
  },
  {
    label: 'Burkina Faso',
    value: 'BurkinaFaso',
    flag: '🇧🇫',
    dialCode: '+226',
  },
  {
    label: 'Burundi',
    value: 'Burundi',
    flag: '🇧🇮',
    dialCode: '+257',
  },
  {
    label: 'Cabo Verde',
    value: 'CaboVerde',
    flag: '🇨🇻',
    dialCode: '+238',
  },
  {
    label: 'Cambodia',
    value: 'Cambodia',
    flag: '🇰🇭',
    dialCode: '+855',
  },
  {
    label: 'Cameroon',
    value: 'Cameroon',
    flag: '🇨🇲',
    dialCode: '+237',
  },
  {
    label: 'Canada',
    value: 'Canada',
    flag: '🇨🇦',
    dialCode: '+1',
  },
  {
    label: 'Central African Republic',
    value: 'CentralAfricanRepublic',
    flag: '🇨🇫',
    dialCode: '+236',
  },
  {
    label: 'Chad',
    value: 'Chad',
    flag: '🇹🇩',
    dialCode: '+235',
  },
  {
    label: 'Chile',
    value: 'Chile',
    flag: '🇨🇱',
    dialCode: '+56',
  },
  {
    label: 'China',
    value: 'China',
    flag: '🇨🇳',
    dialCode: '+86',
  },
  {
    label: 'Colombia',
    value: 'Colombia',
    flag: '🇨🇴',
    dialCode: '+57',
  },
  {
    label: 'Comoros',
    value: 'Comoros',
    flag: '🇰🇲',
    dialCode: '+269',
  },
  {
    label: 'Congo (Congo-Brazzaville)',
    value: 'Congo',
    flag: '🇨🇬',
    dialCode: '+242',
  },
  {
    label: 'Costa Rica',
    value: 'CostaRica',
    flag: '🇨🇷',
    dialCode: '+506',
  },
  {
    label: 'Croatia',
    value: 'Croatia',
    flag: '🇭🇷',
    dialCode: '+385',
  },
  {
    label: 'Cuba',
    value: 'Cuba',
    flag: '🇨🇺',
    dialCode: '+53',
  },
  {
    label: 'Cyprus',
    value: 'Cyprus',
    flag: '🇨🇾',
    dialCode: '+357',
  },
  {
    label: 'Czechia (Czech Republic)',
    value: 'Czechia',
    flag: '🇨🇿',
    dialCode: '+420',
  },
  {
    label: 'Denmark',
    value: 'Denmark',
    flag: '🇩🇰',
    dialCode: '+45',
  },
  {
    label: 'Djibouti',
    value: 'Djibouti',
    flag: '🇩🇯',
    dialCode: '+253',
  },
  {
    label: 'Dominica',
    value: 'Dominica',
    flag: '🇩🇲',
    dialCode: '+1-767',
  },
  {
    label: 'Dominican Republic',
    value: 'DominicanRepublic',
    flag: '🇩🇴',
    dialCode: '+1-809, +1-829, +1-849',
  },
  {
    label: 'Ecuador',
    value: 'Ecuador',
    flag: '🇪🇨',
    dialCode: '+593',
  },
  {
    label: 'Egypt',
    value: 'Egypt',
    flag: '🇪🇬',
    dialCode: '+20',
  },
  {
    label: 'El Salvador',
    value: 'ElSalvador',
    flag: '🇸🇻',
    dialCode: '+503',
  },
  {
    label: 'Equatorial Guinea',
    value: 'EquatorialGuinea',
    flag: '🇬🇶',
    dialCode: '+240',
  },
  {
    label: 'Eritrea',
    value: 'Eritrea',
    flag: '🇪🇷',
    dialCode: '+291',
  },
  {
    label: 'Estonia',
    value: 'Estonia',
    flag: '🇪🇪',
    dialCode: '+372',
  },
  {
    label: 'Eswatini (Swaziland)',
    value: 'Eswatini',
    flag: '🇸🇿',
    dialCode: '+268',
  },
  {
    label: 'Ethiopia',
    value: 'Ethiopia',
    flag: '🇪🇹',
    dialCode: '+251',
  },
  {
    label: 'Fiji',
    value: 'Fiji',
    flag: '🇫🇯',
    dialCode: '+679',
  },
  {
    label: 'Finland',
    value: 'Finland',
    flag: '🇫🇮',
    dialCode: '+358',
  },
  {
    label: 'France',
    value: 'France',
    flag: '🇫🇷',
    dialCode: '+33',
  },
  {
    label: 'Gabon',
    value: 'Gabon',
    flag: '🇬🇦',
    dialCode: '+241',
  },
  {
    label: 'Gambia',
    value: 'Gambia',
    flag: '🇬🇲',
    dialCode: '+220',
  },
  {
    label: 'Georgia',
    value: 'Georgia',
    flag: '🇬🇪',
    dialCode: '+995',
  },
  {
    label: 'Germany',
    value: 'Germany',
    flag: '🇩🇪',
    dialCode: '+49',
  },
  {
    label: 'Ghana',
    value: 'Ghana',
    flag: '🇬🇭',
    dialCode: '+233',
  },
  {
    label: 'Greece',
    value: 'Greece',
    flag: '🇬🇷',
    dialCode: '+30',
  },
  {
    label: 'Grenada',
    value: 'Grenada',
    flag: '🇬🇩',
    dialCode: '+1-473',
  },
  {
    label: 'Guatemala',
    value: 'Guatemala',
    flag: '🇬🇹',
    dialCode: '+502',
  },
  {
    label: 'Guinea',
    value: 'Guinea',
    flag: '🇬🇳',
    dialCode: '+224',
  },
  {
    label: 'Guinea-Bissau',
    value: 'Guinea-Bissau',
    flag: '🇬🇼',
    dialCode: '+245',
  },
  {
    label: 'Guyana',
    value: 'Guyana',
    flag: '🇬🇾',
    dialCode: '+592',
  },
  {
    label: 'Haiti',
    value: 'Haiti',
    flag: '🇭🇹',
    dialCode: '+509',
  },
  {
    label: 'Honduras',
    value: 'Honduras',
    flag: '🇭🇳',
    dialCode: '+504',
  },
  {
    label: 'Hungary',
    value: 'Hungary',
    flag: '🇭🇺',
    dialCode: '+36',
  },
  {
    label: 'Iceland',
    value: 'Iceland',
    flag: '🇮🇸',
    dialCode: '+354',
  },
  {
    label: 'India',
    value: 'India',
    flag: '🇮🇳',
    dialCode: '+91',
  },
  {
    label: 'Indonesia',
    value: 'Indonesia',
    flag: '🇮🇩',
    dialCode: '+62',
  },
  {
    label: 'Iran',
    value: 'Iran',
    flag: '🇮🇷',
    dialCode: '+98',
  },
  {
    label: 'Iraq',
    value: 'Iraq',
    flag: '🇮🇶',
    dialCode: '+964',
  },
  {
    label: 'Ireland',
    value: 'Ireland',
    flag: '🇮🇪',
    dialCode: '+353',
  },
  {
    label: 'Israel',
    value: 'Israel',
    flag: '🇮🇱',
    dialCode: '+972',
  },
  {
    label: 'Italy',
    value: 'Italy',
    flag: '🇮🇹',
    dialCode: '+39',
  },
  {
    label: 'Jamaica',
    value: 'Jamaica',
    flag: '🇯🇲',
    dialCode: '+1-876',
  },
  {
    label: 'Japan',
    value: 'Japan',
    flag: '🇯🇵',
    dialCode: '+81',
  },
  {
    label: 'Jordan',
    value: 'Jordan',
    flag: '🇯🇴',
    dialCode: '+962',
  },
  {
    label: 'Kazakhstan',
    value: 'Kazakhstan',
    flag: '🇰🇿',
    dialCode: '+7',
  },
  {
    label: 'Kenya',
    value: 'Kenya',
    flag: '🇰🇪',
    dialCode: '+254',
  },
  {
    label: 'Kiribati',
    value: 'Kiribati',
    flag: '🇰🇮',
    dialCode: '+686',
  },
  {
    label: 'Kuwait',
    value: 'Kuwait',
    flag: '🇰🇼',
    dialCode: '+965',
  },
  {
    label: 'Kyrgyzstan',
    value: 'Kyrgyzstan',
    flag: '🇰🇬',
    dialCode: '+996',
  },
  {
    label: 'Laos',
    value: 'Laos',
    flag: '🇱🇦',
    dialCode: '+856',
  },
  {
    label: 'Latvia',
    value: 'Latvia',
    flag: '🇱🇻',
    dialCode: '+371',
  },
  {
    label: 'Lebanon',
    value: 'Lebanon',
    flag: '🇱🇧',
    dialCode: '+961',
  },
  {
    label: 'Lesotho',
    value: 'Lesotho',
    flag: '🇱🇸',
    dialCode: '+266',
  },
  {
    label: 'Liberia',
    value: 'Liberia',
    flag: '🇱🇷',
    dialCode: '+231',
  },
  {
    label: 'Libya',
    value: 'Libya',
    flag: '🇱🇾',
    dialCode: '+218',
  },
  {
    label: 'Liechtenstein',
    value: 'Liechtenstein',
    flag: '🇱🇮',
    dialCode: '+423',
  },
  {
    label: 'Lithuania',
    value: 'Lithuania',
    flag: '🇱🇹',
    dialCode: '+370',
  },
  {
    label: 'Luxembourg',
    value: 'Luxembourg',
    flag: '🇱🇺',
    dialCode: '+352',
  },
  {
    label: 'Madagascar',
    value: 'Madagascar',
    flag: '🇲🇬',
    dialCode: '+261',
  },
  {
    label: 'Malawi',
    value: 'Malawi',
    flag: '🇲🇼',
    dialCode: '+265',
  },
  {
    label: 'Malaysia',
    value: 'Malaysia',
    flag: '🇲🇾',
    dialCode: '+60',
  },
  {
    label: 'Maldives',
    value: 'Maldives',
    flag: '🇲🇻',
    dialCode: '+960',
  },
  {
    label: 'Mali',
    value: 'Mali',
    flag: '🇲🇱',
    dialCode: '+223',
  },
  {
    label: 'Malta',
    value: 'Malta',
    flag: '🇲🇹',
    dialCode: '+356',
  },
  {
    label: 'Marshall Islands',
    value: 'MarshallIslands',
    flag: '🇲🇭',
    dialCode: '+692',
  },
  {
    label: 'Mauritania',
    value: 'Mauritania',
    flag: '🇲🇷',
    dialCode: '+222',
  },
  {
    label: 'Mauritius',
    value: 'Mauritius',
    flag: '🇲🇺',
    dialCode: '+230',
  },
  {
    label: 'Mexico',
    value: 'Mexico',
    flag: '🇲🇽',
    dialCode: '+52',
  },
  {
    label: 'Micronesia',
    value: 'Micronesia',
    flag: '🇫🇲',
    dialCode: '+691',
  },
  {
    label: 'Moldova',
    value: 'Moldova',
    flag: '🇲🇩',
    dialCode: '+373',
  },
  {
    label: 'Monaco',
    value: 'Monaco',
    flag: '🇲🇨',
    dialCode: '+377',
  },
  {
    label: 'Mongolia',
    value: 'Mongolia',
    flag: '🇲🇳',
    dialCode: '+976',
  },
  {
    label: 'Montenegro',
    value: 'Montenegro',
    flag: '🇲🇪',
    dialCode: '+382',
  },
  {
    label: 'Morocco',
    value: 'Morocco',
    flag: '🇲🇦',
    dialCode: '+212',
  },
  {
    label: 'Mozambique',
    value: 'Mozambique',
    flag: '🇲🇿',
    dialCode: '+258',
  },
  {
    label: 'Myanmar (Burma)',
    value: 'Myanmar',
    flag: '🇲🇲',
    dialCode: '+95',
  },
  {
    label: 'Namibia',
    value: 'Namibia',
    flag: '🇳🇦',
    dialCode: '+264',
  },
  {
    label: 'Nauru',
    value: 'Nauru',
    flag: '🇳🇷',
    dialCode: '+674',
  },
  {
    label: 'Nepal',
    value: 'Nepal',
    flag: '🇳🇵',
    dialCode: '+977',
  },
  {
    label: 'Netherlands',
    value: 'Netherlands',
    flag: '🇳🇱',
    dialCode: '+31',
  },
  {
    label: 'New Zealand',
    value: 'NewZealand',
    flag: '🇳🇿',
    dialCode: '+64',
  },
  {
    label: 'Nicaragua',
    value: 'Nicaragua',
    flag: '🇳🇮',
    dialCode: '+505',
  },
  {
    label: 'Niger',
    value: 'Niger',
    flag: '🇳🇪',
    dialCode: '+227',
  },
  {
    label: 'Nigeria',
    value: 'Nigeria',
    flag: '🇳🇬',
    dialCode: '+234',
  },
  {
    label: 'North Korea',
    value: 'NorthKorea',
    flag: '🇰🇵',
    dialCode: '+850',
  },
  {
    label: 'North Macedonia',
    value: 'NorthMacedonia',
    flag: '🇲🇰',
    dialCode: '+389',
  },
  {
    label: 'Norway',
    value: 'Norway',
    flag: '🇳🇴',
    dialCode: '+47',
  },
  {
    label: 'Oman',
    value: 'Oman',
    flag: '🇴🇲',
    dialCode: '+968',
  },
  {
    label: 'Pakistan',
    value: 'Pakistan',
    flag: '🇵🇰',
    dialCode: '+92',
  },
  {
    label: 'Palau',
    value: 'Palau',
    flag: '🇵🇼',
    dialCode: '+680',
  },
  {
    label: 'Palestine',
    value: 'Palestine',
    flag: '🇵🇸',
    dialCode: '+970',
  },
  {
    label: 'Panama',
    value: 'Panama',
    flag: '🇵🇦',
    dialCode: '+507',
  },
  {
    label: 'Papua New Guinea',
    value: 'PapuaNewGuinea',
    flag: '🇵🇬',
    dialCode: '+675',
  },
  {
    label: 'Paraguay',
    value: 'Paraguay',
    flag: '🇵🇾',
    dialCode: '+595',
  },
  {
    label: 'Peru',
    value: 'Peru',
    flag: '🇵🇪',
    dialCode: '+51',
  },
  {
    label: 'Philippines',
    value: 'Philippines',
    flag: '🇵🇭',
    dialCode: '+63',
  },
  {
    label: 'Poland',
    value: 'Poland',
    flag: '🇵🇱',
    dialCode: '+48',
  },
  {
    label: 'Portugal',
    value: 'Portugal',
    flag: '🇵🇹',
    dialCode: '+351',
  },
  {
    label: 'Qatar',
    value: 'Qatar',
    flag: '🇶🇦',
    dialCode: '+974',
  },
  {
    label: 'Romania',
    value: 'Romania',
    flag: '🇷🇴',
    dialCode: '+40',
  },
  {
    label: 'Russia',
    value: 'Russia',
    flag: '🇷🇺',
    dialCode: '+7',
  },
  {
    label: 'Rwanda',
    value: 'Rwanda',
    flag: '🇷🇼',
    dialCode: '+250',
  },
  {
    label: 'Saint Kitts and Nevis',
    value: 'SaintKittsandNevis',
    flag: '🇰🇳',
    dialCode: '+1-869',
  },
  {
    label: 'Saint Lucia',
    value: 'SaintLucia',
    flag: '🇱🇨',
    dialCode: '+1-758',
  },
  {
    label: 'Saint Vincent and the Grenadines',
    value: 'SaintVincentandtheGrenadines',
    flag: '🇻🇨',
    dialCode: '+1-784',
  },
  {
    label: 'Samoa',
    value: 'Samoa',
    flag: '🇼🇸',
    dialCode: '+685',
  },
  {
    label: 'San Marino',
    value: 'SanMarino',
    flag: '🇸🇲',
    dialCode: '+378',
  },
  {
    label: 'Sao Tome and Principe',
    value: 'SaoTomeandPrincipe',
    flag: '🇸🇹',
    dialCode: '+239',
  },
  {
    label: 'Saudi Arabia',
    value: 'SaudiArabia',
    flag: '🇸🇦',
    dialCode: '+966',
  },
  {
    label: 'Senegal',
    value: 'Senegal',
    flag: '🇸🇳',
    dialCode: '+221',
  },
  {
    label: 'Serbia',
    value: 'Serbia',
    flag: '🇷🇸',
    dialCode: '+381',
  },
  {
    label: 'Seychelles',
    value: 'Seychelles',
    flag: '🇸🇨',
    dialCode: '+248',
  },
  {
    label: 'Sierra Leone',
    value: 'SierraLeone',
    flag: '🇸🇱',
    dialCode: '+232',
  },
  {
    label: 'Singapore',
    value: 'Singapore',
    flag: '🇸🇬',
    dialCode: '+65',
  },
  {
    label: 'Slovakia',
    value: 'Slovakia',
    flag: '🇸🇰',
    dialCode: '+421',
  },
  {
    label: 'Slovenia',
    value: 'Slovenia',
    flag: '🇸🇮',
    dialCode: '+386',
  },
  {
    label: 'Solomon Islands',
    value: 'SolomonIslands',
    flag: '🇸🇧',
    dialCode: '+677',
  },
  {
    label: 'Somalia',
    value: 'Somalia',
    flag: '🇸🇴',
    dialCode: '+252',
  },
  {
    label: 'South Africa',
    value: 'SouthAfrica',
    flag: '🇿🇦',
    dialCode: '+27',
  },
  {
    label: 'South Korea',
    value: 'SouthKorea',
    flag: '🇰🇷',
    dialCode: '+82',
  },
  {
    label: 'South Sudan',
    value: 'SouthSudan',
    flag: '🇸🇸',
    dialCode: '+211',
  },
  {
    label: 'Spain',
    value: 'Spain',
    flag: '🇪🇸',
    dialCode: '+34',
  },
  {
    label: 'Sri Lanka',
    value: 'SriLanka',
    flag: '🇱🇰',
    dialCode: '+94',
  },
  {
    label: 'Sudan',
    value: 'Sudan',
    flag: '🇸🇩',
    dialCode: '+249',
  },
  {
    label: 'Suriname',
    value: 'Suriname',
    flag: '🇸🇷',
    dialCode: '+597',
  },
  {
    label: 'Sweden',
    value: 'Sweden',
    flag: '🇸🇪',
    dialCode: '+46',
  },
  {
    label: 'Switzerland',
    value: 'Switzerland',
    flag: '🇨🇭',
    dialCode: '+41',
  },
  {
    label: 'Syria',
    value: 'Syria',
    flag: '🇸🇾',
    dialCode: '+963',
  },
  {
    label: 'Taiwan',
    value: 'Taiwan',
    flag: '🇹🇼',
    dialCode: '+886',
  },
  {
    label: 'Tajikistan',
    value: 'Tajikistan',
    flag: '🇹🇯',
    dialCode: '+992',
  },
  {
    label: 'Tanzania',
    value: 'Tanzania',
    flag: '🇹🇿',
    dialCode: '+255',
  },
  {
    label: 'Thailand',
    value: 'Thailand',
    flag: '🇹🇭',
    dialCode: '+66',
  },
  {
    label: 'Timor-Leste',
    value: 'Timor-Leste',
    flag: '🇹🇱',
    dialCode: '+670',
  },
  {
    label: 'Togo',
    value: 'Togo',
    flag: '🇹🇬',
    dialCode: '+228',
  },
  {
    label: 'Tonga',
    value: 'Tonga',
    flag: '🇹🇴',
    dialCode: '+676',
  },
  {
    label: 'Trinidad and Tobago',
    value: 'TrinidadandTobago',
    flag: '🇹🇹',
    dialCode: '+1-868',
  },
  {
    label: 'Tunisia',
    value: 'Tunisia',
    flag: '🇹🇳',
    dialCode: '+216',
  },
  {
    label: 'Turkey',
    value: 'Turkey',
    flag: '🇹🇷',
    dialCode: '+90',
  },
  {
    label: 'Turkmenistan',
    value: 'Turkmenistan',
    flag: '🇹🇲',
    dialCode: '+993',
  },
  {
    label: 'Tuvalu',
    value: 'Tuvalu',
    flag: '🇹🇻',
    dialCode: '+688',
  },
  {
    label: 'Uganda',
    value: 'Uganda',
    flag: '🇺🇬',
    dialCode: '+256',
  },
  {
    label: 'Ukraine',
    value: 'Ukraine',
    flag: '🇺🇦',
    dialCode: '+380',
  },
  {
    label: 'United Arab Emirates',
    value: 'UnitedArabEmirates',
    flag: '🇦🇪',
    dialCode: '+971',
  },
  {
    label: 'United Kingdom',
    value: 'UnitedKingdom',
    flag: '🇬🇧',
    dialCode: '+44',
  },
  {
    label: 'United States',
    value: 'UnitedStates',
    flag: '🇺🇸',
    dialCode: '+1',
  },
  {
    label: 'Uruguay',
    value: 'Uruguay',
    flag: '🇺🇾',
    dialCode: '+598',
  },
  {
    label: 'Uzbekistan',
    value: 'Uzbekistan',
    flag: '🇺🇿',
    dialCode: '+998',
  },
  {
    label: 'Vanuatu',
    value: 'Vanuatu',
    flag: '🇻🇺',
    dialCode: '+678',
  },
  {
    label: 'Vatican City',
    value: 'VaticanCity',
    flag: '🇻🇦',
    dialCode: '+379',
  },
  {
    label: 'Venezuela',
    value: 'Venezuela',
    flag: '🇻🇪',
    dialCode: '+58',
  },
  {
    label: 'Vietnam',
    value: 'Vietnam',
    flag: '🇻🇳',
    dialCode: '+84',
  },
  {
    label: 'Yemen',
    value: 'Yemen',
    flag: '🇾🇪',
    dialCode: '+967',
  },
  {
    label: 'Zambia',
    value: 'Zambia',
    flag: '🇿🇲',
    dialCode: '+260',
  },
  {
    label: 'Zimbabwe',
    value: 'Zimbabwe',
    flag: '🇿🇼',
    dialCode: '+263',
  },
];
