/* eslint-disable no-unused-vars */
import {
  IconBrandTelegram,
  IconCash,
  IconLockDollar,
  IconSchool,
  IconLink,
  IconBrandDiscord,
  IconBrandWhatsapp,
  IconBrandMeta,
  IconCalendarEvent,
  IconArchive,
  IconCreditCardPay,
  IconHome2,
  IconShoppingBag,
  IconUser,
  IconLayoutDashboard,
} from '@tabler/icons-react';

export const SidenavData = [
  {
    icon: IconHome2,
    label: 'Home',
    value: 'Home',
    path: '/home',
  },
  // {
  //   icon: IconArchive,
  //   label: 'Products',
  //   value: 'product',
  //   path: '/product',
  // },
  {
    icon: IconCreditCardPay,
    label: 'Payment',
    value: 'Payment',
    path: '/payment',
  },
  {
    icon: IconShoppingBag,
    label: 'Purchase',
    value: 'purchase',
    path: '/purchase',
  },
  {
    icon: IconUser,
    label: 'Audience',
    value: 'audience',
    path: '/audience',
  },
  {
    icon: IconLink,
    label: 'Short Url',
    value: 'url',
    path: '/links',
  },
  { apps: true },
  {
    icon: IconBrandTelegram,
    label: 'Telegram',
    value: 'tg',
    path: '/app/tg',
  },
  {
    icon: IconLockDollar,
    label: 'Locked Content',
    value: 'lc',
    path: '/app/lc',
  },
  {
    icon: IconSchool,
    label: 'Course',
    value: 'course',
    path: '/app/course',
  },
  {
    icon: IconCash,
    label: 'Digital Product',
    value: 'digitalproduct',
    path: '/app/dp',
  },
  // {
  //   icon: IconBrandDiscord,
  //   label: 'Discord',
  //   value: 'discord',
  //   path: '/app/discord',
  // },
  // {
  //   icon: IconBrandWhatsapp,
  //   label: 'whatsapp',
  //   value: 'whatsapp',
  //   path: '/app/whatsapp',
  // },
  // {
  //   icon: IconBrandMeta,
  //   label: 'meta',
  //   value: 'meta',
  //   path: '/app/meta',
  // },
  // {
  //   icon: IconCalendarEvent,
  //   label: 'Webinar',
  //   value: 'webinar',
  //   path: '/app/webinar',
  // },
];
