import { Inter } from 'next/font/google';
import '@mantine/core/styles.css';
import './globals.css';
import {
  ColorSchemeScript,
  MantineProvider,
  createTheme,
} from '@mantine/core';
import { Notifications } from '@mantine/notifications';

// const inter = Inter({ subsets: ["latin"] });
const theme = createTheme({
  /** Your theme override here */
  colorSchemeManager: 'light',
  forceColorScheme: 'light',
  fontFamily: 'Open Sans, sans-serif',
  primaryColor: 'violet',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head></head>
      <body>
        <ColorSchemeScript forceColorScheme="light" />
        <MantineProvider theme={theme}>
          <Notifications position="top-right" />

          {children}
        </MantineProvider>
      </body>
    </html>
  );
}
