import Footer from '@/Components/Landing/main/ui/Footer';

const page = () => {
  return (
    <div className="mb-4 ml-4 mr-4 flex flex-col items-center gap-4">
      <div className="h-36 w-screen bg-violet-600"></div>

      <div className="prose prose-lg prose-headings:font-bold prose-a:text-blue-600 flex max-w-[750px] flex-col gap-4 p-8 md:p-16">
        Updated as on 5 February 2024 The following
        disclaimer clarifies that Nexify, as an entity,
        shall not be held liable for any content or
        materials published or distributed by a content
        creator on or through any app or website associated
        with us. By using our services, you acknowledge and
        accept the terms of this disclaimer. 1. No
        Endorsement or Control: Nexify provides a platform
        for content creators to share their work, opinions,
        and ideas. However, we do not endorse or take
        responsibility for the accuracy, legality, or
        quality of the content generated by these creators.
        The views and opinions expressed by content creators
        are solely their own and do not represent those
        ofNexify. 2. Third-Party Content: The content and
        materials published or distributed by content
        creators on or through any app or website associated
        with Nexify may include links, references, or
        recommendations to third-party websites, products,
        or services. Nexify does not endorse, guarantee, 3.
        User Discretion and Responsibility: Users of
        {`Nexify's`} services understand and agree that they
        must exercise their own judgment and discretion when
        relying on any content or materials created by
        content creators. It is the responsibility of the
        user to verify the accuracy, completeness, and
        relevance of the information provided by content
        creators. 4. No Warranty or Liability: Nexify makes
        no warranties, express or implied, regarding the
        accuracy, completeness, or availability of any
        content or materials created by content creators. We
        disclaim all liability for any losses, damages, or
        harm arising from the use or reliance on such
        content or materials. This includes but is not
        limited to financial loss, reputational damage, or
        any other direct, indirect, consequential, or
        incidental damages. 5. Content Creator
        Relationships: Nexify may have professional
        relationships or partnerships with content creators,
        but these relationships do not influence or alter
        the independence, objectivity, or integrity of the
        content created by them. The responsibility for the
        accuracy and quality of their content rests solely
        with the respective content creators. 6. Content
        Monitoring and Removal: While Nexify strives to
        maintain a safe and reliable platform, we do not
        actively monitor all content created by content
        creators. While we reserve the right to remove or
        modify any content that violates our policies or
        terms of service, we do not assume liability for any
        content that remains accessible or has been removed.
        7. Indemnification: By using {`Nexify's`} services,
        you agree to indemnify and hold harmless Nexify, its
        employees, officers, directors, and affiliates from
        any claims, damages, losses, liabilities, or
        expenses arising out of or related to your use of
        the content or materials created by content
        creators. It is important to note that this
        disclaimer does not limit or exclude any liability
        that cannot be limited or excluded under applicable
        law. To the extent that any provision of this
        disclaimer is found to be invalid or unenforceable,
        the remaining provisions shall continue to be in
        effect. By using {`Nexify's`} services, you
        acknowledge that you have read, understood, and
        agreed to this disclaimer in its entirety. If you do
        not agree with any part of this disclaimer, you
        should refrain from using {`Nexify's`} services.
      </div>
      <Footer />
    </div>
  );
};

export default page;
